#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/platina

PRODUCT_COPY_FILES += \
    vendor/xiaomi/platina/proprietary/vendor/etc/acdbdata/Forte/Forte_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Bluetooth_cal.acdb \
    vendor/xiaomi/platina/proprietary/vendor/etc/acdbdata/Forte/Forte_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_General_cal.acdb \
    vendor/xiaomi/platina/proprietary/vendor/etc/acdbdata/Forte/Forte_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Global_cal.acdb \
    vendor/xiaomi/platina/proprietary/vendor/etc/acdbdata/Forte/Forte_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Handset_cal.acdb \
    vendor/xiaomi/platina/proprietary/vendor/etc/acdbdata/Forte/Forte_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Hdmi_cal.acdb \
    vendor/xiaomi/platina/proprietary/vendor/etc/acdbdata/Forte/Forte_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Headset_cal.acdb \
    vendor/xiaomi/platina/proprietary/vendor/etc/acdbdata/Forte/Forte_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Speaker_cal.acdb \
    vendor/xiaomi/platina/proprietary/vendor/etc/acdbdata/Forte/Forte_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_workspaceFile.qwsp \
    vendor/xiaomi/platina/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/GpuKernelRepo.pb:$(TARGET_COPY_OUT_VENDOR)/etc/camera/GpuKernelRepo.pb \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/MIUI_Time.ttf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/MIUI_Time.ttf \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/Miui-Light.ttf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/Miui-Light.ttf \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/age_gender_bg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/age_gender_bg \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/beauty_ui9_intelligent_params.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/beauty_ui9_intelligent_params.config \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/crown_156_128.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/crown_156_128.bin \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/csidtg_camera.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/csidtg_camera.xml \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/csidtg_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/csidtg_chromatix.xml \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/dualcamera.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/dualcamera.png \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/eyelineblush.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/eyelineblush.cng \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/face_goodly_208_180:$(TARGET_COPY_OUT_VENDOR)/etc/camera/face_goodly_208_180 \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/face_ravishing_238_224:$(TARGET_COPY_OUT_VENDOR)/etc/camera/face_ravishing_238_224 \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/face_splendid_274_200:$(TARGET_COPY_OUT_VENDOR)/etc/camera/face_splendid_274_200 \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/female_bg.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/female_bg.png \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/female_icon.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/female_icon.png \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/lf_facerank_model.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/lf_facerank_model.bin \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/male_bg.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/male_bg.png \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/male_icon.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/male_icon.png \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/model_back.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model_back.dlc \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/model_front.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model_front.dlc \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/morpho_lowlight4.0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight4.0.xml \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/people_gender.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/people_gender.dat \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/platina_imx363_ofilm_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/platina_imx363_ofilm_chromatix.xml \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/platina_imx363_sunny_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/platina_imx363_sunny_chromatix.xml \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/platina_imx363_sunny_global_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/platina_imx363_sunny_global_chromatix.xml \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/platina_imx576_ofilm_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/platina_imx576_ofilm_chromatix.xml \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/platina_imx576_sunny_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/platina_imx576_sunny_chromatix.xml \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/platina_imx576_sunny_global_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/platina_imx576_sunny_global_chromatix.xml \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/platina_s5k5e8_ofilm_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/platina_s5k5e8_ofilm_chromatix.xml \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/platina_s5k5e8_sunny_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/platina_s5k5e8_sunny_chromatix.xml \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/platina_s5k5e8_sunny_global_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/platina_s5k5e8_sunny_global_chromatix.xml \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/score_bg.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/score_bg.png \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/score_icon.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/score_icon.png \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/sdm_ys_32p_120_21_5_perturb50.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sdm_ys_32p_120_21_5_perturb50.bin \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/watermark_font_2300_3199.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/watermark_font_2300_3199.dat \
    vendor/xiaomi/platina/proprietary/vendor/etc/camera/yuv_test.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/yuv_test.xml \
    vendor/xiaomi/platina/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc \
    vendor/xiaomi/platina/proprietary/vendor/etc/init/android.hardware.keymaster@3.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@3.0-service-qti.rc \
    vendor/xiaomi/platina/proprietary/vendor/etc/permissions/com.fingerprints.extension.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.fingerprints.extension.xml \
    vendor/xiaomi/platina/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/xiaomi/platina/proprietary/vendor/etc/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev.conf \
    vendor/xiaomi/platina/proprietary/vendor/etc/thermal-engine-sdm660-camera.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-sdm660-camera.conf \
    vendor/xiaomi/platina/proprietary/vendor/etc/thermal-engine-sdm660-high.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-sdm660-high.conf \
    vendor/xiaomi/platina/proprietary/vendor/etc/thermal-engine-sdm660-map.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-sdm660-map.conf \
    vendor/xiaomi/platina/proprietary/vendor/etc/thermal-engine-sdm660-nolimits.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-sdm660-nolimits.conf \
    vendor/xiaomi/platina/proprietary/vendor/etc/thermal-engine-sdm660-pubgmhd.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-sdm660-pubgmhd.conf \
    vendor/xiaomi/platina/proprietary/vendor/etc/thermal-engine-sdm660-sgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-sdm660-sgame.conf \
    vendor/xiaomi/platina/proprietary/vendor/etc/thermal-engine-sdm660.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-sdm660.conf \
    vendor/xiaomi/platina/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/xiaomi/platina/proprietary/vendor/firmware/a512_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b00 \
    vendor/xiaomi/platina/proprietary/vendor/firmware/a512_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b01 \
    vendor/xiaomi/platina/proprietary/vendor/firmware/a512_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b02 \
    vendor/xiaomi/platina/proprietary/vendor/firmware/a512_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.elf \
    vendor/xiaomi/platina/proprietary/vendor/firmware/a512_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.mdt \
    vendor/xiaomi/platina/proprietary/vendor/firmware/a530_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_gpmu.fw2 \
    vendor/xiaomi/platina/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    vendor/xiaomi/platina/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    vendor/xiaomi/platina/proprietary/vendor/firmware/a530v1_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v1_pfp.fw \
    vendor/xiaomi/platina/proprietary/vendor/firmware/a530v1_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v1_pm4.fw \
    vendor/xiaomi/platina/proprietary/vendor/firmware/a530v2_seq.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v2_seq.fw2 \
    vendor/xiaomi/platina/proprietary/vendor/firmware/a530v3_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v3_gpmu.fw2 \
    vendor/xiaomi/platina/proprietary/vendor/firmware/a530v3_seq.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v3_seq.fw2 \
    vendor/xiaomi/platina/proprietary/vendor/firmware/a540_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_gpmu.fw2 \
    vendor/xiaomi/platina/proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_10_0.fw \
    vendor/xiaomi/platina/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/xiaomi/platina/proprietary/vendor/firmware/cpp_firmware_v1_12_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_1.fw \
    vendor/xiaomi/platina/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/xiaomi/platina/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/xiaomi/platina/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/xiaomi/platina/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/xiaomi/platina/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/xiaomi/platina/proprietary/vendor/firmware/cpp_firmware_v1_5_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_1.fw \
    vendor/xiaomi/platina/proprietary/vendor/firmware/cpp_firmware_v1_5_2.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_2.fw \
    vendor/xiaomi/platina/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/xiaomi/platina/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw \
    vendor/xiaomi/platina/proprietary/vendor/firmware/dbmd4_va_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dbmd4_va_fw.bin \
    vendor/xiaomi/platina/proprietary/vendor/firmware/tfa98xx_aac.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xx_aac.cnt \
    vendor/xiaomi/platina/proprietary/vendor/firmware/tfa98xx_goer.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xx_goer.cnt \
    vendor/xiaomi/platina/proprietary/vendor/firmware/voice_amodel.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/voice_amodel.bin \
    vendor/xiaomi/platina/proprietary/vendor/lib/mibokeh_660_opencl.bin:$(TARGET_COPY_OUT_VENDOR)/lib/mibokeh_660_opencl.bin

PRODUCT_PACKAGES += \
    activity_recognition.sdm660 \
    android.hardware.gatekeeper@1.0-impl-qti \
    android.hardware.keymaster@3.0-impl-qti \
    libsensor1 \
    libsensor_reg \
    sensors.ssc \
    libFaceGrade \
    libMiCameraHal \
    libSNPE \
    libVDClearShot \
    libVDSuperPhotoAPI \
    libXMFD_AgeGender \
    lib_lowlight \
    libactuator_platina_dw9714_ofilm \
    libactuator_platina_dw9714_sunny \
    libarcsoft_beautyshot \
    libarcsoft_dualcam_refocus \
    libarcsoft_high_dynamic_range \
    libarcsoft_supernight \
    libc++_shared \
    libcamera_scene \
    libchromatix_platina_imx363_ofilm_1080p_preview_3a \
    libchromatix_platina_imx363_ofilm_1080p_video_3a \
    libchromatix_platina_imx363_ofilm_4k_preview_3a \
    libchromatix_platina_imx363_ofilm_4k_video_3a \
    libchromatix_platina_imx363_ofilm_bokeh_preview_3a \
    libchromatix_platina_imx363_ofilm_common \
    libchromatix_platina_imx363_ofilm_cpp_hfr_120 \
    libchromatix_platina_imx363_ofilm_cpp_hfr_240 \
    libchromatix_platina_imx363_ofilm_cpp_hfr_60 \
    libchromatix_platina_imx363_ofilm_cpp_liveshot \
    libchromatix_platina_imx363_ofilm_cpp_preview \
    libchromatix_platina_imx363_ofilm_cpp_preview_bokeh \
    libchromatix_platina_imx363_ofilm_cpp_snapshot \
    libchromatix_platina_imx363_ofilm_cpp_snapshot_bokeh \
    libchromatix_platina_imx363_ofilm_cpp_snapshot_downscale \
    libchromatix_platina_imx363_ofilm_cpp_snapshot_hdr \
    libchromatix_platina_imx363_ofilm_cpp_snapshot_hht \
    libchromatix_platina_imx363_ofilm_cpp_snapshot_sn \
    libchromatix_platina_imx363_ofilm_cpp_snapshot_sr \
    libchromatix_platina_imx363_ofilm_cpp_snapshot_upscale \
    libchromatix_platina_imx363_ofilm_cpp_video \
    libchromatix_platina_imx363_ofilm_cpp_video_4k \
    libchromatix_platina_imx363_ofilm_cpp_video_hdr \
    libchromatix_platina_imx363_ofilm_cpp_video_weixin \
    libchromatix_platina_imx363_ofilm_default_preview_3a \
    libchromatix_platina_imx363_ofilm_default_video \
    libchromatix_platina_imx363_ofilm_default_video_3a \
    libchromatix_platina_imx363_ofilm_fullsize_preview_3a \
    libchromatix_platina_imx363_ofilm_fullsize_preview_3a_sn \
    libchromatix_platina_imx363_ofilm_fullsize_video_3a \
    libchromatix_platina_imx363_ofilm_hfr_120 \
    libchromatix_platina_imx363_ofilm_hfr_120_3a \
    libchromatix_platina_imx363_ofilm_hfr_240 \
    libchromatix_platina_imx363_ofilm_hfr_240_3a \
    libchromatix_platina_imx363_ofilm_hfr_60 \
    libchromatix_platina_imx363_ofilm_hfr_60_3a \
    libchromatix_platina_imx363_ofilm_panorama_preview_3a \
    libchromatix_platina_imx363_ofilm_postproc \
    libchromatix_platina_imx363_ofilm_preview \
    libchromatix_platina_imx363_ofilm_preview_bokeh \
    libchromatix_platina_imx363_ofilm_snapshot \
    libchromatix_platina_imx363_ofilm_snapshot_bokeh \
    libchromatix_platina_imx363_ofilm_snapshot_panorama \
    libchromatix_platina_imx363_ofilm_snapshot_sn \
    libchromatix_platina_imx363_ofilm_video \
    libchromatix_platina_imx363_ofilm_video_4k \
    libchromatix_platina_imx363_ofilm_video_weixin \
    libchromatix_platina_imx363_ofilm_weixin_video_3a \
    libchromatix_platina_imx363_sunny_1080p_preview_3a \
    libchromatix_platina_imx363_sunny_1080p_video_3a \
    libchromatix_platina_imx363_sunny_4k_preview_3a \
    libchromatix_platina_imx363_sunny_4k_video_3a \
    libchromatix_platina_imx363_sunny_bokeh_preview_3a \
    libchromatix_platina_imx363_sunny_common \
    libchromatix_platina_imx363_sunny_cpp_hfr_120 \
    libchromatix_platina_imx363_sunny_cpp_hfr_240 \
    libchromatix_platina_imx363_sunny_cpp_hfr_60 \
    libchromatix_platina_imx363_sunny_cpp_liveshot \
    libchromatix_platina_imx363_sunny_cpp_preview \
    libchromatix_platina_imx363_sunny_cpp_preview_bokeh \
    libchromatix_platina_imx363_sunny_cpp_snapshot \
    libchromatix_platina_imx363_sunny_cpp_snapshot_bokeh \
    libchromatix_platina_imx363_sunny_cpp_snapshot_downscale \
    libchromatix_platina_imx363_sunny_cpp_snapshot_hdr \
    libchromatix_platina_imx363_sunny_cpp_snapshot_hht \
    libchromatix_platina_imx363_sunny_cpp_snapshot_sn \
    libchromatix_platina_imx363_sunny_cpp_snapshot_sr \
    libchromatix_platina_imx363_sunny_cpp_snapshot_upscale \
    libchromatix_platina_imx363_sunny_cpp_video \
    libchromatix_platina_imx363_sunny_cpp_video_4k \
    libchromatix_platina_imx363_sunny_cpp_video_hdr \
    libchromatix_platina_imx363_sunny_cpp_video_weixin \
    libchromatix_platina_imx363_sunny_default_preview_3a \
    libchromatix_platina_imx363_sunny_default_video \
    libchromatix_platina_imx363_sunny_default_video_3a \
    libchromatix_platina_imx363_sunny_fullsize_preview_3a \
    libchromatix_platina_imx363_sunny_fullsize_preview_3a_sn \
    libchromatix_platina_imx363_sunny_fullsize_video_3a \
    libchromatix_platina_imx363_sunny_global_1080p_preview_3a \
    libchromatix_platina_imx363_sunny_global_1080p_video_3a \
    libchromatix_platina_imx363_sunny_global_4k_preview_3a \
    libchromatix_platina_imx363_sunny_global_4k_video_3a \
    libchromatix_platina_imx363_sunny_global_bokeh_preview_3a \
    libchromatix_platina_imx363_sunny_global_common \
    libchromatix_platina_imx363_sunny_global_cpp_hfr_120 \
    libchromatix_platina_imx363_sunny_global_cpp_hfr_240 \
    libchromatix_platina_imx363_sunny_global_cpp_hfr_60 \
    libchromatix_platina_imx363_sunny_global_cpp_liveshot \
    libchromatix_platina_imx363_sunny_global_cpp_preview \
    libchromatix_platina_imx363_sunny_global_cpp_preview_bokeh \
    libchromatix_platina_imx363_sunny_global_cpp_snapshot \
    libchromatix_platina_imx363_sunny_global_cpp_snapshot_bokeh \
    libchromatix_platina_imx363_sunny_global_cpp_snapshot_downscale \
    libchromatix_platina_imx363_sunny_global_cpp_snapshot_hdr \
    libchromatix_platina_imx363_sunny_global_cpp_snapshot_hht \
    libchromatix_platina_imx363_sunny_global_cpp_snapshot_sn \
    libchromatix_platina_imx363_sunny_global_cpp_snapshot_sr \
    libchromatix_platina_imx363_sunny_global_cpp_snapshot_upscale \
    libchromatix_platina_imx363_sunny_global_cpp_video \
    libchromatix_platina_imx363_sunny_global_cpp_video_4k \
    libchromatix_platina_imx363_sunny_global_cpp_video_hdr \
    libchromatix_platina_imx363_sunny_global_cpp_video_weixin \
    libchromatix_platina_imx363_sunny_global_default_preview_3a \
    libchromatix_platina_imx363_sunny_global_default_video \
    libchromatix_platina_imx363_sunny_global_default_video_3a \
    libchromatix_platina_imx363_sunny_global_fullsize_preview_3a \
    libchromatix_platina_imx363_sunny_global_fullsize_preview_3a_sn \
    libchromatix_platina_imx363_sunny_global_fullsize_video_3a \
    libchromatix_platina_imx363_sunny_global_hfr_120 \
    libchromatix_platina_imx363_sunny_global_hfr_120_3a \
    libchromatix_platina_imx363_sunny_global_hfr_240 \
    libchromatix_platina_imx363_sunny_global_hfr_240_3a \
    libchromatix_platina_imx363_sunny_global_hfr_60 \
    libchromatix_platina_imx363_sunny_global_hfr_60_3a \
    libchromatix_platina_imx363_sunny_global_panorama_preview_3a \
    libchromatix_platina_imx363_sunny_global_postproc \
    libchromatix_platina_imx363_sunny_global_preview \
    libchromatix_platina_imx363_sunny_global_preview_bokeh \
    libchromatix_platina_imx363_sunny_global_snapshot \
    libchromatix_platina_imx363_sunny_global_snapshot_bokeh \
    libchromatix_platina_imx363_sunny_global_snapshot_panorama \
    libchromatix_platina_imx363_sunny_global_snapshot_sn \
    libchromatix_platina_imx363_sunny_global_video \
    libchromatix_platina_imx363_sunny_global_video_4k \
    libchromatix_platina_imx363_sunny_global_video_weixin \
    libchromatix_platina_imx363_sunny_global_weixin_video_3a \
    libchromatix_platina_imx363_sunny_hfr_120 \
    libchromatix_platina_imx363_sunny_hfr_120_3a \
    libchromatix_platina_imx363_sunny_hfr_240 \
    libchromatix_platina_imx363_sunny_hfr_240_3a \
    libchromatix_platina_imx363_sunny_hfr_60 \
    libchromatix_platina_imx363_sunny_hfr_60_3a \
    libchromatix_platina_imx363_sunny_panorama_preview_3a \
    libchromatix_platina_imx363_sunny_postproc \
    libchromatix_platina_imx363_sunny_preview \
    libchromatix_platina_imx363_sunny_preview_bokeh \
    libchromatix_platina_imx363_sunny_snapshot \
    libchromatix_platina_imx363_sunny_snapshot_bokeh \
    libchromatix_platina_imx363_sunny_snapshot_panorama \
    libchromatix_platina_imx363_sunny_snapshot_sn \
    libchromatix_platina_imx363_sunny_video \
    libchromatix_platina_imx363_sunny_video_4k \
    libchromatix_platina_imx363_sunny_video_weixin \
    libchromatix_platina_imx363_sunny_weixin_video_3a \
    libchromatix_platina_imx576_ofilm_1080p_preview_3a \
    libchromatix_platina_imx576_ofilm_1080p_video_3a \
    libchromatix_platina_imx576_ofilm_4k_preview_3a \
    libchromatix_platina_imx576_ofilm_4k_video_3a \
    libchromatix_platina_imx576_ofilm_common \
    libchromatix_platina_imx576_ofilm_cpp_hfr_120 \
    libchromatix_platina_imx576_ofilm_cpp_liveshot \
    libchromatix_platina_imx576_ofilm_cpp_preview \
    libchromatix_platina_imx576_ofilm_cpp_snapshot \
    libchromatix_platina_imx576_ofilm_cpp_snapshot_6m \
    libchromatix_platina_imx576_ofilm_cpp_snapshot_6m_hht \
    libchromatix_platina_imx576_ofilm_cpp_snapshot_downscale \
    libchromatix_platina_imx576_ofilm_cpp_snapshot_hdr \
    libchromatix_platina_imx576_ofilm_cpp_snapshot_upscale \
    libchromatix_platina_imx576_ofilm_cpp_video \
    libchromatix_platina_imx576_ofilm_cpp_video_4k \
    libchromatix_platina_imx576_ofilm_cpp_video_weixin \
    libchromatix_platina_imx576_ofilm_default_preview_3a \
    libchromatix_platina_imx576_ofilm_default_video_3a \
    libchromatix_platina_imx576_ofilm_face_video_3a \
    libchromatix_platina_imx576_ofilm_fullsize_preview_3a \
    libchromatix_platina_imx576_ofilm_fullsize_video_3a \
    libchromatix_platina_imx576_ofilm_hfr_120 \
    libchromatix_platina_imx576_ofilm_hfr_120_3a \
    libchromatix_platina_imx576_ofilm_postproc \
    libchromatix_platina_imx576_ofilm_preview \
    libchromatix_platina_imx576_ofilm_snapshot \
    libchromatix_platina_imx576_ofilm_snapshot_hdr \
    libchromatix_platina_imx576_ofilm_video \
    libchromatix_platina_imx576_ofilm_video_4k \
    libchromatix_platina_imx576_ofilm_video_face \
    libchromatix_platina_imx576_ofilm_video_weixin \
    libchromatix_platina_imx576_ofilm_weixin_video_3a \
    libchromatix_platina_imx576_sunny_1080p_preview_3a \
    libchromatix_platina_imx576_sunny_1080p_video_3a \
    libchromatix_platina_imx576_sunny_4k_preview_3a \
    libchromatix_platina_imx576_sunny_4k_video_3a \
    libchromatix_platina_imx576_sunny_common \
    libchromatix_platina_imx576_sunny_cpp_hfr_120 \
    libchromatix_platina_imx576_sunny_cpp_liveshot \
    libchromatix_platina_imx576_sunny_cpp_preview \
    libchromatix_platina_imx576_sunny_cpp_snapshot \
    libchromatix_platina_imx576_sunny_cpp_snapshot_6m \
    libchromatix_platina_imx576_sunny_cpp_snapshot_6m_hht \
    libchromatix_platina_imx576_sunny_cpp_snapshot_downscale \
    libchromatix_platina_imx576_sunny_cpp_snapshot_hdr \
    libchromatix_platina_imx576_sunny_cpp_snapshot_upscale \
    libchromatix_platina_imx576_sunny_cpp_video \
    libchromatix_platina_imx576_sunny_cpp_video_4k \
    libchromatix_platina_imx576_sunny_cpp_video_weixin \
    libchromatix_platina_imx576_sunny_default_preview_3a \
    libchromatix_platina_imx576_sunny_default_video_3a \
    libchromatix_platina_imx576_sunny_face_video_3a \
    libchromatix_platina_imx576_sunny_fullsize_preview_3a \
    libchromatix_platina_imx576_sunny_fullsize_video_3a \
    libchromatix_platina_imx576_sunny_global_1080p_preview_3a \
    libchromatix_platina_imx576_sunny_global_1080p_video_3a \
    libchromatix_platina_imx576_sunny_global_4k_preview_3a \
    libchromatix_platina_imx576_sunny_global_4k_video_3a \
    libchromatix_platina_imx576_sunny_global_common \
    libchromatix_platina_imx576_sunny_global_cpp_hfr_120 \
    libchromatix_platina_imx576_sunny_global_cpp_liveshot \
    libchromatix_platina_imx576_sunny_global_cpp_preview \
    libchromatix_platina_imx576_sunny_global_cpp_snapshot \
    libchromatix_platina_imx576_sunny_global_cpp_snapshot_6m \
    libchromatix_platina_imx576_sunny_global_cpp_snapshot_6m_hht \
    libchromatix_platina_imx576_sunny_global_cpp_snapshot_hdr \
    libchromatix_platina_imx576_sunny_global_cpp_snapshot_upscale \
    libchromatix_platina_imx576_sunny_global_cpp_video \
    libchromatix_platina_imx576_sunny_global_cpp_video_4k \
    libchromatix_platina_imx576_sunny_global_cpp_video_weixin \
    libchromatix_platina_imx576_sunny_global_default_preview_3a \
    libchromatix_platina_imx576_sunny_global_default_video_3a \
    libchromatix_platina_imx576_sunny_global_face_video_3a \
    libchromatix_platina_imx576_sunny_global_fullsize_preview_3a \
    libchromatix_platina_imx576_sunny_global_fullsize_video_3a \
    libchromatix_platina_imx576_sunny_global_hfr_120 \
    libchromatix_platina_imx576_sunny_global_hfr_120_3a \
    libchromatix_platina_imx576_sunny_global_postproc \
    libchromatix_platina_imx576_sunny_global_preview \
    libchromatix_platina_imx576_sunny_global_snapshot \
    libchromatix_platina_imx576_sunny_global_snapshot_hdr \
    libchromatix_platina_imx576_sunny_global_video \
    libchromatix_platina_imx576_sunny_global_video_4k \
    libchromatix_platina_imx576_sunny_global_video_face \
    libchromatix_platina_imx576_sunny_global_video_weixin \
    libchromatix_platina_imx576_sunny_global_weixin_video_3a \
    libchromatix_platina_imx576_sunny_hfr_120 \
    libchromatix_platina_imx576_sunny_hfr_120_3a \
    libchromatix_platina_imx576_sunny_postproc \
    libchromatix_platina_imx576_sunny_preview \
    libchromatix_platina_imx576_sunny_snapshot \
    libchromatix_platina_imx576_sunny_snapshot_hdr \
    libchromatix_platina_imx576_sunny_video \
    libchromatix_platina_imx576_sunny_video_4k \
    libchromatix_platina_imx576_sunny_video_face \
    libchromatix_platina_imx576_sunny_video_weixin \
    libchromatix_platina_imx576_sunny_weixin_video_3a \
    libchromatix_platina_s5k5e8_ofilm_a3_zsl_preview \
    libchromatix_platina_s5k5e8_ofilm_a3_zsl_video \
    libchromatix_platina_s5k5e8_ofilm_common \
    libchromatix_platina_s5k5e8_ofilm_cpp_liveshot \
    libchromatix_platina_s5k5e8_ofilm_cpp_preview \
    libchromatix_platina_s5k5e8_ofilm_cpp_snapshot \
    libchromatix_platina_s5k5e8_ofilm_cpp_snapshot_4m \
    libchromatix_platina_s5k5e8_ofilm_cpp_video \
    libchromatix_platina_s5k5e8_ofilm_postproc \
    libchromatix_platina_s5k5e8_ofilm_preview \
    libchromatix_platina_s5k5e8_ofilm_snapshot \
    libchromatix_platina_s5k5e8_sunny_a3_zsl_preview \
    libchromatix_platina_s5k5e8_sunny_a3_zsl_video \
    libchromatix_platina_s5k5e8_sunny_common \
    libchromatix_platina_s5k5e8_sunny_cpp_liveshot \
    libchromatix_platina_s5k5e8_sunny_cpp_preview \
    libchromatix_platina_s5k5e8_sunny_cpp_snapshot \
    libchromatix_platina_s5k5e8_sunny_cpp_snapshot_4m \
    libchromatix_platina_s5k5e8_sunny_cpp_video \
    libchromatix_platina_s5k5e8_sunny_global_a3_zsl_preview \
    libchromatix_platina_s5k5e8_sunny_global_a3_zsl_video \
    libchromatix_platina_s5k5e8_sunny_global_common \
    libchromatix_platina_s5k5e8_sunny_global_cpp_liveshot \
    libchromatix_platina_s5k5e8_sunny_global_cpp_preview \
    libchromatix_platina_s5k5e8_sunny_global_cpp_snapshot \
    libchromatix_platina_s5k5e8_sunny_global_cpp_snapshot_4m \
    libchromatix_platina_s5k5e8_sunny_global_cpp_video \
    libchromatix_platina_s5k5e8_sunny_global_postproc \
    libchromatix_platina_s5k5e8_sunny_global_preview \
    libchromatix_platina_s5k5e8_sunny_global_snapshot \
    libchromatix_platina_s5k5e8_sunny_postproc \
    libchromatix_platina_s5k5e8_sunny_preview \
    libchromatix_platina_s5k5e8_sunny_snapshot \
    libdepthmapwrapper \
    libflash_pmic \
    libft2vendor \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmibokeh_660 \
    libmm-qcamera \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_is \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera2_stats_modules \
    libmmcamera_arcsoftbokeh_lib \
    libmmcamera_atmel_at24c32e_eeprom \
    libmmcamera_bokeh \
    libmmcamera_csidtg \
    libmmcamera_depth_map \
    libmmcamera_dummyalgo \
    libmmcamera_dw9761b_2d_eeprom \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hvx_add_constant \
    libmmcamera_hvx_grid_sum \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_imx214 \
    libmmcamera_imx230 \
    libmmcamera_imx258 \
    libmmcamera_imx258_gt24c16_eeprom \
    libmmcamera_imx258_gt24c32_eeprom \
    libmmcamera_imx258_mono \
    libmmcamera_imx258_mono_gt24c32_eeprom \
    libmmcamera_imx298 \
    libmmcamera_imx318 \
    libmmcamera_imx362 \
    libmmcamera_imx362_gt24c64a \
    libmmcamera_imx376 \
    libmmcamera_imx378 \
    libmmcamera_imx519 \
    libmmcamera_irs1645 \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_bpc48 \
    libmmcamera_isp_cac47 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic48 \
    libmmcamera_isp_demux48 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic48 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr48 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_hdr_bhist_stats44 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm47 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pdaf48 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_snr47 \
    libmmcamera_isp_sub_module \
    libmmcamera_le2464c_eeprom \
    libmmcamera_le2464c_master_eeprom \
    libmmcamera_m24c64s_eeprom \
    libmmcamera_mg_facepp_lib \
    libmmcamera_ofilm_ohs0443_ov12a10_eeprom \
    libmmcamera_ofilm_ohs0443_ov13880_eeprom \
    libmmcamera_onsemi_cat24c16_eeprom \
    libmmcamera_onsemi_cat24c32_eeprom \
    libmmcamera_onsemi_cat24c32_imx362_eeprom \
    libmmcamera_ov12a10 \
    libmmcamera_ov13850 \
    libmmcamera_ov13850_q13v06k \
    libmmcamera_ov13855 \
    libmmcamera_ov13880 \
    libmmcamera_ov2281 \
    libmmcamera_ov2680 \
    libmmcamera_ov2685 \
    libmmcamera_ov2685_scv3b4035 \
    libmmcamera_ov4188 \
    libmmcamera_ov4688 \
    libmmcamera_ov4688_eeprom \
    libmmcamera_ov5645 \
    libmmcamera_ov5670 \
    libmmcamera_ov5695 \
    libmmcamera_ov7251 \
    libmmcamera_ov8856 \
    libmmcamera_ov8856_2lane \
    libmmcamera_ov8856_4lane \
    libmmcamera_ov8858 \
    libmmcamera_ov8865 \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_platina_imx363_bl24sa64_ofilm_eeprom \
    libmmcamera_platina_imx363_gt24p64ba8_sunny_eeprom \
    libmmcamera_platina_imx363_ofilm \
    libmmcamera_platina_imx363_sunny \
    libmmcamera_platina_imx576_bl24sa64_ofilm_eeprom \
    libmmcamera_platina_imx576_gt24p64ba2_sunny_eeprom \
    libmmcamera_platina_imx576_ofilm \
    libmmcamera_platina_imx576_sunny \
    libmmcamera_platina_s5k5e8_ofilm \
    libmmcamera_platina_s5k5e8_ofilm_eeprom \
    libmmcamera_platina_s5k5e8_sunny \
    libmmcamera_platina_s5k5e8_sunny_eeprom \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_qtech_f3l8yam_eeprom \
    libmmcamera_qtech_f5670bq_eeprom \
    libmmcamera_quadracfa \
    libmmcamera_rohm_brcg064gwz_3_eeprom \
    libmmcamera_s5k2l7 \
    libmmcamera_s5k2l7sx \
    libmmcamera_s5k3l8 \
    libmmcamera_s5k3l8_mono \
    libmmcamera_s5k3m2xm \
    libmmcamera_s5k3m2xx \
    libmmcamera_s5k3m3sm \
    libmmcamera_s5k3p3sm \
    libmmcamera_s5k3p8sp \
    libmmcamera_s5k5e9yu05 \
    libmmcamera_sony_imx214_eeprom \
    libmmcamera_sony_imx298_eeprom \
    libmmcamera_sony_imx378_eeprom \
    libmmcamera_sonyimx135_eeprom \
    libmmcamera_stillmore_lib \
    libmmcamera_sunny_8865_eeprom \
    libmmcamera_sunny_gt24c64_imx298_eeprom \
    libmmcamera_sunny_gt24c64_s5k2l7_eeprom \
    libmmcamera_sunny_gt24c64_s5k2l7sx_eeprom \
    libmmcamera_sunny_gt24c64a_imx362_eeprom \
    libmmcamera_sunny_gt24c64a_imx376_eeprom \
    libmmcamera_sunny_gt24p64b_imx519_eeprom \
    libmmcamera_sunny_ov13855_eeprom \
    libmmcamera_sunny_q13v06k_eeprom \
    libmmcamera_sunny_q5v41b_eeprom \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmcamera_truly_cma481_eeprom \
    libmmcamera_truly_cmb433_eeprom \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmjpeg \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libmorphohht4.0 \
    libmpbase \
    libois_bu63165 \
    libois_lc898122 \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libremosaic_daemon \
    libseemore \
    libsymphony-cpu \
    libsymphonypower \
    libvideoutils \
    libvidhance \
    libvidhance_gyro \
    fingerprint.fpc.default \
    fingerprint.goodix.default \
    libgf_ca \
    libgf_hal \
    libthermalioctl \
    com.fingerprints.extension \
    cnss-daemon \
    android.hardware.gatekeeper@1.0-service-qti \
    android.hardware.keymaster@3.0-service-qti \
    sensors.qti \
    thermal-engine
